:PROPERTIES:
:ID:       c0068aab-77da-421d-9cb8-3609fc6c4c69
:END:
#+title: Discrete-Set
#+date: [2022-01-28 Fri 09:15]
#+author: Amar Panji Senjaya

#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{positioning}
#+OPTIONS: \n:t
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage[margin=1in]{pgfplots}
\pgfplotsset{ compat=1.3, compat/path replacement=1.5.1,}
#+LATEX: \setlength\parindent{0pt}
#+LATEX_HEADER: \renewcommand{\Large}{\normalsize}
#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@ @@ascii:|@@
#+LATEX: \newpage

Source And Learning Material:
https://www.youtube.com/playlist?list=PLHXZ9OQGMqxersk8fUxiUMSIx0DBqsKZS
https://www.amazon.com/Discrete-Mathematics-Applications-Susanna-Epp/dp/1337694193/ref=sr_1_2?keywords=discrete+math&qid=1645043639&sr=8-2

* What is Set
A *set* is a collection of objects. Individual object of set is element \in. Individual object of element that is not in The set is  called not in element denoted with \notin.
** Examples
- A = Employees in a company
  John \in A
- B = {1,3,4,7}
  3 \in A
  \pi \notin B
- Z = Integers
  3 \in Z

** Order And Repetition Don't Matter
#+BEGIN_SRC markdown
{1, 2, 3, 4, 5, 6, 7} = {2, 5, 4, 3, 1, 7, 6}
            = {2, 2, 2, 2, 5, 4, 3, 1, 1, 7, 6, 6, 6}
#+end_src

#+LATEX: \newpage

* Subsets
- Every Element of A is also in B = A \subseteq B
*** Example 1
A = {1, 3}
B = {1, 3, 4, 6}
A \subseteq B
*** Example 2
A = {1, 8}
B = {1, 3, 4, 6}
A \nsubseteq B
because \in 8 is not in B

* Set-Roster Notion
Replace ... with continuos clear pattern
Example:
Positive even integers
{0, 2, 4, 6, ...}
all even integers
{..., -6, -4, -2, 0, 2, 4, 6, ...}

* Set-Builder Notation
General form: { x | P(x) }
x variable
"|" such that
P(x) Property is true
Example even integers
= { x | x = Twice an integer }
Example square root
{ x | \sqrt{x} \in \mathbb{Z} }

#+LATEX: \newpage

* Empty Set
Notion: {} or \emptyset
{\emptyset}
Is \emptyset \subset {1,2,3}?
Recall: A \subset B means:
if x \in A, then x \in B
This is /vacuously/ true!

* Ordered Pairs (/a/, /b/)
- Order Matters
- (a,b) = (c,d) of a=c & b=d
- a&b could come from different sets

_Defn_: The cartesian product A \times B is the set of all ordered pairs (a,b) where a \in A and b \in B

#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={p},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both]
#+LATEX: \addplot coordinates{(2,1)};
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

p = (2,1) \in \mathbb{R} x \mathbb{R}
first component is x axis and second component is y axis

Example:
{a,b} \times {0,1}
A \times B = {(a,1), (a,0), (b,0), (b1)}

* Relations
Ex: a < b
compares two integers
some pairs have this relationship 2 < 5
some pairs don't 5 \nless 2

note:
h: human
d: dog
c: cat
m: monkey
\begin{tikzpicture}[
mydot/.style={
  circle,
  fill,
  inner sep=2pt
},
>=latex,
shorten >= 3pt,
shorten <= 3pt
]
\node[mydot,label={left:h1}] (h1) {}; 
\node[mydot,below=of h1,label={left:h2}] (h2) {}; 
\node[mydot,below=of h2,label={left:h3}] (h3) {}; 
\node[mydot,below=of h3,label={left:h4}] (h4) {}; 

\node[mydot,right=2cm of h1,label={right:d1}] (d1) {}; 
\node[mydot,below=of d1,label={right:c1}] (c1) {}; 
\node[mydot,below=of c1,label={right:d2}] (d2) {}; 
\node[mydot,below=of d2,label={right:m1}] (m1) {}; 

\path[->] (h1) edge (c1);
\path[->] (h2) edge (d1);
\path[->] (h3) edge (d1);
\end{tikzpicture}

_defn_: A Relation R between A and B is a subset of A \times B

ie ordered pairs
(a,b) \in A \times B
* Functions
ex: f(x) = x^2

#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={f},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both]
#+LATEX: \addplot {(x^2)};
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

function do something to every input in my domain and produce output for each input

domain: set of all possible input
range: set of all possible output

_Defn_: A function F between A and B
is a relation between A and B such that:
subset of A \times B

1) For every x \in A there is an element y \in B such that (x,y) \in F
   Which means
   Fo every input x, there is some ouput y, F(x)=y
2) If (x,y) \in F and (x,z) \in F then y = z


Example: Is this relation?
Consider the relation C where (x,y) \in C if x^2 + y^2 = 1. Is this a function?
#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={f},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both, extra tick style={grid=major}]
#+LATEX: \addplot coordinates{(0,1)};
#+LATEX: \draw (axis cs:0,0) circle[radius=1];
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

This is relation but not a function because there is more than one output asociated with one input


* Statement
A statement is a sentence that is either true or false

Examples:
p: "5 > 2" = True
q: "2 > 5" = False
r: "x > 2" = Not a statement because we don't know what x is

** New statement from old
\neg p means not p
p \land q means p and q
p \lor q means p or q

Example:
"My shirt is gray but my shorts are not"
p = My shirt is gray
q = My shorts are gray
p\land \neg q

** Truth Table for (\neg p) \lor (\neg q)
| p | q | \neg p | \neg q |   |
|---+---+--------+--------+---|
| T | T | F      | F      | F |
| T | F | F      | T      | T |
| F | T | T      | F      | T |
| F | F | T      | T      | T |

Def: Two statements are logically equivalent if they have the same truth table
| p | \neg p | \neg (\neg p) |
|---+--------+---------------|
| T | F      | T             |
| F | T      | F             |

Def: A tautology t is a statement that is always true
Example:
That dog is a mammal

t: tautology
p: some statement
| t | p | t \lor p |
|---+---+----------|
| T | T | T        |
| T | F | T        |


Def: A contrandiction c is a statement that is always false
Example:
That dog is a reptile

c: contrandiction
p: some statement
| c | p | c \land p |
|---+---+-----------|
| F | T | F         |
| F | F | F         |

so c \land p is a contrandiction

#+LATEX: \newpage
* Demorgan's Law & Logical Equivalent
p: Trefor is a unicorn
q: Trefor is a goldfish
\neg(p \lor q) \equiv (\neg p) \land (\neg q)?
It's NOT the case that Trefor is either a unicorn OR a goldfish.
is equivalent to:
Trefor is NOT a unicorn AND is NOT a goldfish.

| p | q | \neg p | \neg q | p \lor q | \neg (p \land q) | (\neg p) \land (\neg q) |
|---+---+--------+--------+----------+------------------+-------------------------|
| T | T | F      | F      | T        | F                | F                       |
| T | F | F      | T      | T        | F                | F                       |
| F | T | T      | F      | T        | F                | F                       |
| F | F | T      | T      | F        | T                | T                       |

Demorgan's Laws:
\neg (p \lor q) \equiv (\neg p) \land (\neg q)
\neg (p \land q) \equiv (\neg p) \lor (\neg q)

Double Negative:
\neg(\neg p) \equiv p

Identity Laws:
p \lor c \equiv p
p \land t \equiv p

Universal Bound Laws:
p \lor t \equiv t
p \land c \equiv c

Example:
(\neg(p \lor \neg q)) \land t
via DeMorgan's
\equiv (\neg p \land \neg (\neg q)) \land t
via Double Negative
\equiv (\neg p \land q) \land t
Via Identity
\equiv \neg p \land q

So (\neg(p \lor \neg q)) \land t \equiv \neg p \land q

#+LATEX: \newpage
* Conditional Statement
Def: p \Rightarrow q means:
"if p is TRUE then q is TRUE"
Whenever the hipotesis p is true then the conclution is also true.

| p | q | p \Rightarrow q |
|---+---+-----------------|
| T | T | T               |
| T | F | F               |
| F | T | T               |
| F | F | T               |

| \neg p | \neg p \lor q |
|--------+---------------|
| F      | T             |
| F      | F             |
| T      | T             |
| T      | T             |

p \Rightarrow q \equiv \neg p \lor q

Example:
If i study hard, then i will pass
p = i study hard
q = i will pass
p \Rightarrow q

Either I don't study hard, or i pass
\neg p = I don't study hard
q = i pass

** When the hypothesis is false, the statement is *vacuously true*.
vacuously true meant the statement is true but true in a sort of unimportant or unintresting or vacuous set.

Example:
If _Trefor is a unicorn_, then _everyone get's an A_
p = Trefor is a unicorn
q = everyone get's an A
p \Rightarrow q

Example:
Either _Trefor is not a unicorn_, or _everyone get's an A_
\neg p = Trefor is not a unicorn
q =  everyone get's an A
\neg p \lor q

** Negating a conditional
\neg (p \Rightarrow q) \equiv \neg (\neg p \lor q)
\equiv (\neg \neg p \land \neg q) Demorgan's law
\equiv p \land \neg q

** Contrapositive of a conditional:
p \Rightarrow q \equiv \neg q \Rightarrow \neg p
p \Rightarrow q \equiv  \neg p \lor q
\neg q \Rightarrow \neg p \equiv q \lor \neg p


If i study hard, then i will pass p \Rightarrow q
Either I don't study hard, or i pass \neg p \lor \q
If i don't pass, then i didn't study hard \q \Rightarrow \neg p
Either i pass, or I didn't study hard q \lor \neg p

** The converse and the inverse of a statement
*** The converse statement
p \Rightarrow q is the statement q \Rightarrow p
The converse statement is not logically equivalent

Example:
Not Logically equivalent
p \Rightarrow q = If it's a dog, then it's a mammal = True
q \Rightarrow p = If it's a mammal, then it's a dog = False

*** The inverse statement
p \Rightarrow q is the statement \neg p \Rightarrow \neg q
The inverse statements is not logically equivalent

So inverse \equiv converse

Example
Not Logically equivalent
p \Rightarrow q = If it's a dog, then it's a mammal = True
\neg p \Rightarrow \neg q = If it's not a dog, then it's not a mammal = False

** Biconditional statement
The Biconditional p \iff q
means that both p \Rightarrow q and q \Rightarrow p

Example
If i study hard, then I will pass = p \Rightarrow q
_AND_ if I pass, then I studied hard = q \Rightarrow p

i will pass *if and only if* i study hard
if and only if = \iff

** Valid and Invalid Arguments
A valid argument is a list of premises from which the conclusion follows.

Example Argument:
If _I do the dishes_, then _my wife will be happy with me_.
_I do the dishes_.
Therefore, _my wife is happy with me_.

If *p*, then *q*.
*p*.
Therefore, *q*.

*** Modus Ponens
*Modus Ponens* is an argument of the form:
premise1 = If *p*, then *q*.
premise2 = *p*.
conclusion = Therefore, *q*.

Variables
| p | q |
|---+---|
| T | T |
| T | F |
| F | F |
| F | T |

Premises
| p \Rightarrow q | p |
|-----------------+---|
| T               | T |
| F               | T |
| T               | F |
| T               | F |

Conclusion
| q |
|---|
| T |
| X |
| X |
| X |

*** Modus Tollens
*Modus Tollens* is an argument of the form:
if *p*, then *q*.
\neg q.
Therefore, \neg p.

example argument:
If i'm POTUS then i'm an American citizen.
I'm not an American citizen.
Therefore, I'm not the POTUS.

p = i'm POTUS
q = i'm an American citizen.
\neg q = I'm not an American citizen.
\neg p = I'm not the POTUS.

*** Generalization
*Generalization* is an argument of the form:
p.
Therefore, p \lor q.

Example:
i'm a canadian
Therefore, I'm a canadian or i'm a unicorn.


*** Specialization
*Specialization* is an argument of the form:
p \land q.
Therefore, p.

Example:
I'm a canadian _and_ I have a PhD
Therefore, I'm a Canadian.


*** Contradiction
*Contradiction* is an argument of the form:
\neg p \Rightarrow c
Therefore, p.

Example:
If i'm skilled at poker, then I will win.
I won money playing poker.
Therefore, I'm skilled at poker.

p = i'm skilled at poker
q = I will win.
q = I won money playing poker.
p = I'm skilled at poker.

p \Rightarrow q
q
p

This argument is invalid argument because it's use converse statement.
We know converse statement is not logically equivalent.


* Predicates and Quantified Statements
Recall: A statement is either TRUE or FALSE
** Predicate
a *predicate* is a sentence depending on variables which becomes a sttemnt upon substituting values in the domain.

Example:
P(x): x is a factor of 12 with domain \mathbb{Z}^{+}

P(6) True
P(5) False
P(\(\frac{1}{3}\)) Nonsense! \(\frac{1}{3}\) \notin \mathbb{Z}^{+}

** The Truth set
*The truth set* of a predicate P(x):
{x \in \mathbb{D} | P(x)}
i.e All values x in the domain where P(x) is true

Example:
P(x): x is a factor of 12 with domain \mathbb{Z}^{+}
TS = {1, 2, 3, 4, 5, 6, 12}
\subseteq \mathbb{Z}^{+}

** The Universal Quantifier
*The Universal Quantifier \forall* means "for all"

Main Use "quantifying" predicates
\forall x \in D, P(x)
For all x in the domain, P(x) is true

Example:
Every dog is a mammal
\forall
D = set of dogs ; P(x): X is a mammal

** The existensial quantifier
*The existensial quantifier \exists* means "there exists"

Main use "quantifying" predicates
\exist x \in D, P(x)
There exists x in the domain, such that P(x)is true

Ex: Some person is the oldest in the world
\exist \in {People in the world}; P(x): X is the oldest

statement P: "Roofus is a mammal"
predicate P(x): "x is a mammal"
statement Q: \forall x \in D, P(x): "every dog is a mammal"

** Negating quantifier
Negate "\forall x \in \mathbb{Z}^{+}, x > 3"
\exist x \in \mathbb{Z}^{+ },x \ngtr 3
\exist x \in \mathbb{Z}^{+ },x\leq 3
\neg P(x)

Negating a universal
\neg (\forall x \mathbb{D}, P(x)) \equiv x \in \mathbb{D}, \neg P(x).

Example:
Negate "Someone in our class it taller than 7 feet"
\exist x \in D, P(x)
D = our class
P(x) = x is taller than 7 feet.

negation:
\neg(\exist x \in D, P(x))
everyone in our class is shorter than 7 feet
\forall x \in D, \neg P(x)

Negating an existensial
\neg (\exist x \in D, P(x)) \equiv \forall x \in D, \neg P(x).

** Negating logical statement
Example
Every interger has a larger integer
\forall x \in \mathbb{Z}, P(x)

\forall x \in \mathbb{Z}, \exist y \in \mathbb{Z}, y > x
P(x) = \exist y \in \mathbb{Z}, y > x

True: choose y = x + 1 \in \mathbb{Z}

Negate: \exist x \in \mathbb{Z}, \neg P(x)
\exist x \in \mathbb{Z}, \forall y \in \mathbb{Z}, y \lteq x

Example:
Some number in D is the largest
\exist x \in D, P(x)
\exist x \in D, \forall y \in D, X \grteq y

Negate: \forall x \in D, \exist y \in D, x < y

** Universal Conditionals
Universal-Conditionals: P(x) \Rightarrow Q(x)
means \forall x \in D, P(x) \Rightarrow Q(x)

Example:
if x is the POTUS, then x is a US Citizen
P(x) = x is the POTUS
Q(x) = x is a US Citizen
D = people

** Necessary and Sufficient Conditions
Square
\begin{tikzpicture}
\draw[ultra thick, blue] (0,0) -- (1,0) -- (1,1) -- (0,1) -- (0,0);
\end{tikzpicture}

Rectangle
\begin{tikzpicture}
\draw[green!70!dark, ultra thick] (0,0) -- (1.5,0) -- (1.5,1) -- (0,1) -- (0,0);
\end{tikzpicture}

Quadrilateral
\begin{tikzpicture}
\draw[red,ultra thick] (0,0) -- (0.9,1) -- (1,-0.3) -- (0.4, -0.5) -- (0,0);
\end{tikzpicture}

All Squares are Rectangles
if x is a Square, then x is a Rectangle
if A(x), then B(x)

A(x) is a sufficient condition for B(x)
i.e. "x being a square is sufficient to conclude x is a rectangle"

if x is a Rectangle, then x is a Quadrilateral
if B(x), then C(x)

if x is not a Quadrilateral then x is not a Rectangle
if \neg C(x), then \neg B(x)

sufficient to have a Square = A(x)
if we want a rectangle = B(x)
But necessary to have a Quadrilateral C(x)
A(x) \Rightarrow B(x) \Rightarrow C(x)
A(x) is a sufficient condition for B(x)
B(x) is a necessary condition for A(x)

Being a square is a sufficient condition fo being a rectangle
Being a rectangle is a necesary condition for being a square

* Defining Even & Odd Integers
Informal Definition: n is an even integer if n can be written as twice an integer.
Formal Definition: n is an even integer if \exist k \in \mathbb{Z} such that n = 2k

Informal Definition: n is an odd integer if n is an integer that is not even.
Formal Definition: n is an odd integer if \exist k \in \mathbb{Z} such that n = 2k + 1

* Mathematical Proof
** First Proof
Theorem: an even integer plus an odd integer is another odd integer
Proof:
Suppose m is even and n is odd.
\exist k_1 \in Z and \exist k_2 \in Z that m = 2k_1 and n = 2k_2 + 1

Then, m + n = (2k_1)+(2k_2 + 1)
= 2(k_1 + k_2) + 1
Let k_3 = k_1 + k_2, and note it is an integer.

Hence, \exist k_3 \in Z so that m + n = 2k_3 + 1
Thus m + n is odd.

Direct Proofs of: \forall x \in D, P(x) \Rightarrow Q(x)
1 State the Assumptions
2 Formally Define the assumptions
3 Manipulate
4 Arrive at Definition of conclusion
5 state the conclusion
** Product of two even is even
Theorem: an *even integer* times an *even integer* is another *even integer*

Step 1: Define terms
Informal Definition: n is an *even integer* if n can be written as twice an integer.
Formal Definition: For n an integer:
n is even \iff \exist p \in Z
So that n = 2p           

Step 2: State Theorem Formally
Theorem Formally: \forall m, n \in Z if m, n are even,
then mn is even

Format: \forall x \in D, P(x) \Rightarrow Q(x)

Step 3: Play around!
4 . 8 = 32
4 =  2 . 2
8 = 2 . 4
32 = 2(2) * 2(4)
= 2(2 . 2 . 4)

Step 4: actual Proof

Start with Assumptions

Apply Definitions

Use algebra, known theorems, logical inferences, etc

get to the conclusion

Proof:
Suppose m and n are even integers.
As m, n are even, \exist r and \exist s so that m = 2r and n = 2s.
Then, mn = (2r)(2s) by substitutiion
= 2(2rs) by algebra
Let t = 2rs, and note it is an integer.
Hence, \exist t \in Z so that mn=2t
Thus mn is even.


** Rational numbers definition + first proof

** Proving that divisibility is transitive

** Disproving implications with counterexamples

** 
