:PROPERTIES:
:ID:       c0068aab-77da-421d-9cb8-3609fc6c4c69
:END:
#+title: Discrete-Set
#+date: [2022-01-28 Fri 09:15]
#+author: Amar Panji Senjaya

#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{positioning}
#+OPTIONS: \n:t
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage[margin=1in]{pgfplots}
\pgfplotsset{ compat=1.3, compat/path replacement=1.5.1,}
#+LATEX: \setlength\parindent{0pt}
#+LATEX_HEADER: \renewcommand{\Large}{\normalsize}
#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@ @@ascii:|@@
#+LATEX: \newpage

Source And Learning Material:
https://www.youtube.com/playlist?list=PLHXZ9OQGMqxersk8fUxiUMSIx0DBqsKZS
https://www.amazon.com/Discrete-Mathematics-Applications-Susanna-Epp/dp/1337694193/ref=sr_1_2?keywords=discrete+math&qid=1645043639&sr=8-2

* What is Set
A *set* is a collection of objects. Individual object of set is element \in. Individual object of element that is not in The set is  called not in element denoted with \notin.
** Examples
- A = Employees in a company
  John \in A
- B = {1,3,4,7}
  3 \in A
  \pi \notin B
- Z = Integers
  3 \in Z

** Order And Repetition Don't Matter
#+BEGIN_SRC markdown
{1, 2, 3, 4, 5, 6, 7} = {2, 5, 4, 3, 1, 7, 6}
            = {2, 2, 2, 2, 5, 4, 3, 1, 1, 7, 6, 6, 6}
#+end_src

#+LATEX: \newpage

* Subsets
- Every Element of A is also in B = A \subseteq B
*** Example 1
A = {1, 3}
B = {1, 3, 4, 6}
A \subseteq B
*** Example 2
A = {1, 8}
B = {1, 3, 4, 6}
A \nsubseteq B
because \in 8 is not in B

* Set-Roster Notion
Replace ... with continuos clear pattern
Example:
Positive even integers
{0, 2, 4, 6, ...}
all even integers
{..., -6, -4, -2, 0, 2, 4, 6, ...}

* Set-Builder Notation
General form: { x | P(x) }
x variable
"|" such that
P(x) Property is true
Example even integers
= { x | x = Twice an integer }
Example square root
{ x | \sqrt{x} \in \mathbb{Z} }

#+LATEX: \newpage

* Empty Set
Notion: {} or \emptyset
{\emptyset}
Is \emptyset \subset {1,2,3}?
Recall: A \subset B means:
if x \in A, then x \in B
This is /vacuously/ true!

* Ordered Pairs (/a/, /b/)
- Order Matters
- (a,b) = (c,d) of a=c & b=d
- a&b could come from different sets

_Defn_: The cartesian product A \times B is the set of all ordered pairs (a,b) where a \in A and b \in B

#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={p},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both]
#+LATEX: \addplot coordinates{(2,1)};
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

p = (2,1) \in \mathbb{R} x \mathbb{R}
first component is x axis and second component is y axis

Example:
{a,b} \times {0,1}
A \times B = {(a,1), (a,0), (b,0), (b1)}

* Relations
Ex: a < b
compares two integers
some pairs have this relationship 2 < 5
some pairs don't 5 \nless 2

note:
h: human
d: dog
c: cat
m: monkey
\begin{tikzpicture}[
mydot/.style={
  circle,
  fill,
  inner sep=2pt
},
>=latex,
shorten >= 3pt,
shorten <= 3pt
]
\node[mydot,label={left:h1}] (h1) {}; 
\node[mydot,below=of h1,label={left:h2}] (h2) {}; 
\node[mydot,below=of h2,label={left:h3}] (h3) {}; 
\node[mydot,below=of h3,label={left:h4}] (h4) {}; 

\node[mydot,right=2cm of h1,label={right:d1}] (d1) {}; 
\node[mydot,below=of d1,label={right:c1}] (c1) {}; 
\node[mydot,below=of c1,label={right:d2}] (d2) {}; 
\node[mydot,below=of d2,label={right:m1}] (m1) {}; 

\path[->] (h1) edge (c1);
\path[->] (h2) edge (d1);
\path[->] (h3) edge (d1);
\end{tikzpicture}

_defn_: A Relation R between A and B is a subset of A \times B

ie ordered pairs
(a,b) \in A \times B
* Functions
ex: f(x) = x^2

#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={f},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both]
#+LATEX: \addplot {(x^2)};
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

function do something to every input in my domain and produce output for each input

domain: set of all possible input
range: set of all possible output

_Defn_: A function F between A and B
is a relation between A and B such that:
subset of A \times B

1) For every x \in A there is an element y \in B such that (x,y) \in F
   Which means
   Fo every input x, there is some ouput y, F(x)=y
2) If (x,y) \in F and (x,z) \in F then y = z


Example: Is this relation?
Consider the relation C where (x,y) \in C if x^2 + y^2 = 1. Is this a function?
#+LATEX: \begin{tikzpicture}
#+LATEX: \begin{axis}[legend entries={f},ymin=-2,ymax=2,xmin=-2,xmax=2, axis lines=middle,axis equal,grid=both, extra tick style={grid=major}]
#+LATEX: \addplot coordinates{(0,1)};
#+LATEX: \draw (axis cs:0,0) circle[radius=1];
#+LATEX: \end{axis}
#+LATEX: \end{tikzpicture}

This is relation but not a function because there is more than one output asociated with one input


* Statement
A statement is a sentence that is either true or false

Examples:
p: "5 > 2" = True
q: "2 > 5" = False
r: "x > 2" = Not a statement because we don't know what x is

** New statement from old
\neg p means not p
p \land q means p and q
p \lor q means p or q

Example:
"My shirt is gray but my shorts are not"
p = My shirt is gray
q = My shorts are gray
p\land \neg q

** Truth Table for (\neg p) \lor (\neg q)
| p | q | \neg p | \neg q |   |
|---+---+--------+--------+---|
| T | T | F      | F      | F |
| T | F | F      | T      | T |
| F | T | T      | F      | T |
| F | F | T      | T      | T |

Def: Two statements are logically equivalent if they have the same truth table
| p | \neg p | \neg (\neg p) |
|---+--------+---------------|
| T | F      | T             |
| F | T      | F             |

Def: A tautology t is a statement that is always true
Example:
That dog is a mammal

t: tautology
p: some statement
| t | p | t \lor p |
|---+---+----------|
| T | T | T        |
| T | F | T        |


Def: A contrandiction c is a statement that is always false
Example:
That dog is a reptile

c: contrandiction
p: some statement
| c | p | c \land p |
|---+---+-----------|
| F | T | F         |
| F | F | F         |

so c \land p is a contrandiction

* Demorgan's Law & Logical Equivalent
p: Trefor is a unicorn
q: Trefor is a goldfish
\neg(p \lor q) \equiv (\neg p) \land (\neg q)?
It's NOT the case that Trefor is either a unicorn OR a goldfish.
is equivalent to:
Trefor is NOT a unicorn AND is NOT a goldfish.

| p | q | \neg p | \neg q | p \lor q | \neg (p \land q) | (\neg p) \land (\neg q) |
|---+---+--------+--------+----------+------------------+-------------------------|
| T | T | F      | F      | T        | F                | F                       |
| T | F | F      | T      | T        | F                | F                       |
| F | T | T      | F      | T        | F                | F                       |
| F | F | T      | T      | F        | T                | T                       |

Demorgan's Laws:
\neg (p \lor q) \equiv (\neg p) \land (\neg q)
\neg (p \land q) \equiv (\neg p) \lor (\neg q)

Double Negative:
\neg(\neg p) \equiv p

Identity Laws:
p \lor c \equiv p
p \land t \equiv p

Universal Bound Laws:
p \lor t \equiv t
p \land c \equiv c

Example:
(\neg(p \lor \neg q)) \land t
via DeMorgan's
\equiv (\neg p \land \neg (\neg q)) \land t
via Double Negative
\equiv (\neg p \land q) \land t
Via Identity
\equiv \neg p \land q
